### ISSUE TITLE
Use macros for 'magic' strings.

### ISSUE THREAD

**Issue by jensboe** [xemeds/obstruction-game#6]
I don't know what `\033[0;36m` means, Some control or color instructions maybe. So i must google it.
Something like a macro `#define CLI_CYAN_COLOR \033[0;36m` make your code easily understandable. Trust me in 6 month you don't know the color codes any more and you must google by yourself.

**Comment by xemeds** [comment]
I already forgot what the color codes were. I will definitely add macros to make it more understandable. 
So lets say I defined this: `#define CLI_CYAN_COLOR \033[0;36m`
And I wanted to print a cyan _Hello_
How would I do that?

**Comment by jensboe** [comment]
`#define CLI_CYAN_COLOR "\033[0;36m"` Use quotes.
`printf(CLI_CYAN_COLOR "Hello");`
If you want to see what the precompiler does, add -E flag to gcc.
`gcc -E file1.c `

But that disadvantage of this approach is, that it will leave the CLI cyan. Maybe a custom printf_cyan()
 function is better?
```
printf_cyan() // Definition musst look like orginal printf (which looks complicated and I don't look for it)
{
    returntypOfprintf returnvalue; // Only if printf has one
    printf(CLI_CYAN_COLOR);
    returnvalue = print(/*Arguments*/):
    printf(CLI_DEFAULT_COLOR);
    return returnvalue;
}
```

**Comment by xemeds** [comment]
Thank you for the clarification. There is a color code to reset back to normal. I will probably use that.
